name: BXGo

on:
  push:
    branches: [ bx ]
  pull_request:
    branches: [ bx ]
  schedule:
    - cron:  '0 4 * * *'
  workflow_run:
    workflows: ["Go"]
    types: [requested]
    branches:
      - 'master'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.4.60
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip uninstall cryptography
          pip install cryptography==36.0.2
    
      - name: run
        run: STD_ID='${{ secrets.BX_STD_ID }}' PASSWORD='${{ secrets.BX_PASSWORD }}' python3 main.py
